quarkus:
  http:
    cors: true
  datasource:
    username: service
    password: service
    db-kind: mariadb
    jdbc:
      url: jdbc:mysql://localhost:3306/watchable_watchnext
omdb:
  base-url: http://www.omdbapi.com/
  # api-key from env variables
